/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import { StIndexedDB as StIndexeddb } from './components/st-indexeddb/st-indexeddb';

interface HTMLStIndexeddbElement extends StIndexeddb, HTMLElement {
}
declare var HTMLStIndexeddbElement: {
  prototype: HTMLStIndexeddbElement;
  new (): HTMLStIndexeddbElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "st-indexeddb": HTMLStIndexeddbElement;
  }
  interface ElementTagNameMap {
      "st-indexeddb": HTMLStIndexeddbElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "st-indexeddb": JSXElements.StIndexeddbAttributes;
      }
  }
  namespace JSXElements {
      export interface StIndexeddbAttributes extends HTMLAttributes {
          mode?: string,
          color?: string,
        
          openDatabase?: any,
          getByKey?: any,
          getAll?: any,
          add?: any,
          update?: any,
          delete?: any,
          openCursor?: any,
          clear?: any,
          getByIndex?: any,
          dbName?: string,
          version?: number
      }
  }
}

